# Generated by Django 5.1.6 on 2025-02-06 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_active",
        ),
    ]
