# Generated by Django 5.1.6 on 2025-02-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0004_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                choices=[
                    ("AP", "Andhra Pradesh"),
                    ("AR", "Arunachal Pradesh"),
                    ("AS", "Assam"),
                    ("BR", "Bihar"),
                    ("CG", "Chhattisgarh"),
                    ("GA", "Goa"),
                    ("GJ", "Gujarat"),
                    ("HR", "Haryana"),
                    ("HP", "Himachal Pradesh"),
                    ("JH", "Jharkhand"),
                    ("KA", "Karnataka"),
                    ("KL", "Kerala"),
                    ("MP", "Madhya Pradesh"),
                    ("MH", "Maharashtra"),
                    ("MN", "Manipur"),
                    ("ML", "Meghalaya"),
                    ("MZ", "Mizoram"),
                    ("NL", "Nagaland"),
                    ("OD", "Odisha"),
                    ("PB", "Punjab"),
                    ("RJ", "Rajasthan"),
                    ("SK", "Sikkim"),
                    ("TN", "Tamil Nadu"),
                    ("TG", "Telangana"),
                    ("TR", "Tripura"),
                    ("UP", "Uttar Pradesh"),
                    ("UK", "Uttarakhand"),
                    ("WB", "West Bengal"),
                    ("AN", "Andaman and Nicobar Islands"),
                    ("CH", "Chandigarh"),
                    ("DN", "Dadra and Nagar Haveli and Daman and Diu"),
                    ("LD", "Lakshadweep"),
                    ("DL", "Delhi"),
                    ("PY", "Puducherry"),
                    ("JK", "Jammu & Kashmir"),
                    ("LA", "Ladakh"),
                ],
                max_length=100,
            ),
        ),
    ]
